### ISSUE TITLE
Doesn't look support vscodium

### ISSUE THREAD

**Issue by camlafit** [Gruntfuggly/bettercomment#6]
Hello

I use vscodium 1.47.3 and this extension is not available in market.
```
Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-28T10:50:43.978Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.19.0-10-amd64
```

Is it possible to support it ?

Thanks a lot :)

**Comment by Gruntfuggly** [comment]
What is required to make it available in the market? Can you give me a link to the market?

**Comment by camlafit** [comment]
Hello

When I do :  Ctrl+P ; ext install Gruntfuggly.bettercomment
I get an empty result : 
![Capture d’écran de 2020-08-06 11-26-19](https://user-images.githubusercontent.com/209915/89515669-bb632980-d7d7-11ea-9d97-c926377a8de6.png)

I don't know if vscodium add a filter on extionsion result.

**Comment by Gruntfuggly** [comment]
Looks like I need to publish to another marketplace. I'll try and do it later today.

**Comment by Gruntfuggly** [comment]
It should now be available.

**Comment by camlafit** [comment]
Hello

Looks great \o/ 
![Capture d’écran de 2020-08-07 09-48-07](https://user-images.githubusercontent.com/209915/89622346-350c1d80-d893-11ea-8c11-093981420398.png)

Thanks a lot
